version: "3"
services:
  backend:
    build: ./backend
    tty: true
    volumes:
      - ./backend:/usr/local/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - TZ=Asia/Tokyo
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
